package gui;

import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import database.DBConnection;


public class GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public GUI() {
        initComponents();
        loadChuyenBay();
        loadKhachHang();
        loadVe();
        jTabbedPane6.addChangeListener(e -> {
            int index = jTabbedPane6.getSelectedIndex();

            if (index == 0) {
                loadChuyenBay();
            } else if (index == 1) {
                loadKhachHang();
            } else if (index == 2) {
                loadVe();
            } else if (index == 3) {
                loadCTKM();
            }
        });
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnThem_cb = new javax.swing.JButton();
        btnXoa_cb = new javax.swing.JButton();
        btnTim_cb = new javax.swing.JButton();
        btnSua_cb = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cb = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnThem_kh = new javax.swing.JButton();
        btnXoa_kh = new javax.swing.JButton();
        btnTim_kh = new javax.swing.JButton();
        btnSua_kh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_kh = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnThem_ve = new javax.swing.JButton();
        btnXoa_ve = new javax.swing.JButton();
        btnTim_ve = new javax.swing.JButton();
        btnSua_ve = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_ve = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        btnThem_ctkm = new javax.swing.JButton();
        btnXoa_ctkm = new javax.swing.JButton();
        btnTim_ctkm = new javax.swing.JButton();
        btnSua_ctkm = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnThongKe = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnBaoCao = new javax.swing.JButton();
        btnXuatHoaDon = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("HỆ THỐNG QUẢN LÝ CHUYẾN BAY");
        jTextField1.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTextField1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        btnThem_cb.setText("Thêm");
        btnThem_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_cbActionPerformed(evt);
            }
        });

        btnXoa_cb.setText("Xóa");
        btnXoa_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_cbActionPerformed(evt);
            }
        });

        btnTim_cb.setText("Tìm Kiếm");
        btnTim_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim_cbActionPerformed(evt);
            }
        });

        btnSua_cb.setText("Sửa");
        btnSua_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_cbActionPerformed(evt);
            }
        });

        tbl_cb.setAutoCreateRowSorter(true);
        tbl_cb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã CB", "Mã Máy Bay", "Mã HHK", "Nơi Đi", "Nơi Đến", 
                "Ngày Bay", "Giờ Bay", "Giờ Đến", "Tổng Vé", "Đã Bán", "Còn Lại", "Tiền Vé"
            }
        ));
        tbl_cb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_cb.setDoubleBuffered(true);
        jScrollPane1.setViewportView(tbl_cb);
        if (tbl_cb.getColumnModel().getColumnCount() > 0) {
            tbl_cb.getColumnModel().getColumn(5).setResizable(false);
            tbl_cb.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnThem_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnXoa_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSua_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnTim_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem_cb)
                    .addComponent(btnXoa_cb)
                    .addComponent(btnTim_cb)
                    .addComponent(btnSua_cb))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Quản Lý Chuyến Bay", jPanel7);

        btnThem_kh.setText("Thêm");
        btnThem_kh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_khActionPerformed(evt);
            }
        });

        btnXoa_kh.setText("Xóa");
        btnXoa_kh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_khActionPerformed(evt);
            }
        });

        btnTim_kh.setText("Tìm Kiếm");
        btnTim_kh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim_khActionPerformed(evt);
            }
        });

        btnSua_kh.setText("Sửa");
        btnSua_kh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_khActionPerformed(evt);
            }
        });

        tbl_kh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Họ", "Tên", "Mã Hãng Hàng Không", "Ngày Sinh", "SDT", "Email"
            }
        ));
        jScrollPane2.setViewportView(tbl_kh);
        if (tbl_kh.getColumnModel().getColumnCount() > 0) {
            tbl_kh.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnThem_kh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnXoa_kh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSua_kh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnTim_kh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem_kh)
                    .addComponent(btnXoa_kh)
                    .addComponent(btnTim_kh)
                    .addComponent(btnSua_kh))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Quản Lý Khách Hàng", jPanel8);

        btnThem_ve.setText("Thêm");
        btnThem_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_veActionPerformed(evt);
            }
        });

        btnXoa_ve.setText("Xóa");
        btnXoa_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_veActionPerformed(evt);
            }
        });

        btnTim_ve.setText("Tìm Kiếm");
        btnTim_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim_veActionPerformed(evt);
            }
        });

        btnSua_ve.setText("Sửa");
        btnSua_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_veActionPerformed(evt);
            }
        });

        tbl_ve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Vé", "Mã Chuyến Bay", "Mã Ghế", "Loại Vé", "Giá Vé"
            }
        ));
        jScrollPane3.setViewportView(tbl_ve);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnThem_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnXoa_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSua_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnTim_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem_ve)
                    .addComponent(btnXoa_ve)
                    .addComponent(btnTim_ve)
                    .addComponent(btnSua_ve))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Quản Lý Vé", jPanel10);

        btnThem_ctkm.setText("Thêm");
        btnThem_ctkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_ctkmActionPerformed(evt);
            }
        });

        btnXoa_ctkm.setText("Xóa");
        btnXoa_ctkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_ctkmActionPerformed(evt);
            }
        });

        btnTim_ctkm.setText("Tìm Kiếm");
        btnTim_ctkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim_ctkmActionPerformed(evt);
            }
        });

        btnSua_ctkm.setText("Sửa");
        btnSua_ctkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_ctkmActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khuyến Mãi", "Tên", "Giá Trị", "Ngày bắt đầu", "Ngày kết thúc", "Điều Kiện Áp Dụng", "Trạng Thái"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnThem_ctkm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnXoa_ctkm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSua_ctkm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnTim_ctkm, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem_ctkm)
                    .addComponent(btnXoa_ctkm)
                    .addComponent(btnTim_ctkm)
                    .addComponent(btnSua_ctkm))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Quản Lý CTKM", jPanel12);

        btnThongKe.setText("Thống Kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnHoaDon.setText("Xem Hóa Đơn");
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        btnBaoCao.setText("Báo Cáo");
        btnBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaoCaoActionPerformed(evt);
            }
        });

        btnXuatHoaDon.setText("Xuất Hóa Đơn");
        btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHoaDonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane6.addTab("Báo Cáo", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    
    // ========================= SỰ KIỆN CHO QUẢN LÝ CHUYẾN BAY ========================
    private void btnDoc_cbActionPerformed(java.awt.event.ActionEvent evt) {                                          
    // Lấy model của bảng Chuyến Bay trong NetBeans
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tbl_cb.getModel();
    model.setRowCount(0); // Xóa sạch dữ liệu cũ trên bảng
    
    // Gọi DAO lấy danh sách (Nhớ đổi docTatCa() thành selectAll() nếu DAO của bạn dùng tên đó)
    DAO.ChuyenBayDAO dao = new DAO.ChuyenBayDAO();
    java.util.ArrayList<model.ChuyenBay> list = dao.docTatCa();
    
    // Đổ dữ liệu mới vào
    for (model.ChuyenBay cb : list) {
        model.addRow(new Object[]{
            cb.getMaChuyenBay(), cb.getMaMayBay(), cb.getMaHangHangKhong(),
            cb.getMaSanBayDi(), cb.getMaSanBayDen(), cb.getNgayBay(),
            cb.getGioBay(), cb.getGioDen(), cb.getTongSoVe(),
            cb.getSoVeDaBan(), cb.getSoVeConLai(), cb.getTienVeThuVe()
        });
    }
}
    private void btnTim_cbActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String maCB = JOptionPane.showInputDialog(this, "Nhập mã Chuyến Bay:");

        if (maCB != null && !maCB.trim().isEmpty()) {
            try {
                Connection conn = DBConnection.getConnection();

                String sql = "SELECT * FROM chuyenbay WHERE maCB = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, maCB);

                ResultSet rs = ps.executeQuery();

                DefaultTableModel model = (DefaultTableModel) tbl_cb.getModel();
                model.setRowCount(0);

                if (rs.next()) {
                    model.addRow(new Object[]{
                    rs.getString("maChuyenBay"),
                    rs.getString("maMayBay"),
                    rs.getString("maHangHangKhong"),
                    rs.getString("maSanBayDi"),
                    rs.getString("maSanBayDen"),
                    rs.getString("NgayBay"),
                    rs.getString("GioBay"),
                    rs.getString("GioDen"),
                    rs.getInt("TongSoVe"),
                    rs.getInt("SoVeDaBan"),
                    rs.getInt("SoVeConLai"),
                    rs.getLong("TienVeThuVe")
                    });
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy!");
                }

                conn.close();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    private void btnSua_cbActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        JFrame frame = new JFrame("Sửa Thông Tin Chuyến Bay ");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 500);
        
        JTextField txtMaChuyenBay = new JTextField();
        JTextField txtHHK = new JTextField();
        JTextField txtDiemDen = new JTextField();
        JTextField txtDiemDi= new JTextField();
        JTextField txtNgayBay= new JTextField();
        JTextField txtTongVe = new JTextField();
        JTextField txtDaBan = new JTextField();
        JTextField txtConLai = new JTextField();
        
        frame.add(new JLabel("Mã Chuyến Bay:"));
        frame.add(txtMaChuyenBay);
        frame.add(new JLabel("Hãng Hàng Không:"));
        frame.add(txtHHK);
        frame.add(new JLabel("Điểm Đến:"));
        frame.add(txtDiemDen);
        frame.add(new JLabel("Điểm Đi:"));
        frame.add(txtDiemDi);
        frame.add(new JLabel("Ngày Bay:"));
        frame.add(txtNgayBay);
        frame.add(new JLabel("Tổng Vé:"));
        frame.add(txtTongVe);
        frame.add(new JLabel("Đã Bán:"));
        frame.add(txtDaBan);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {
            try {
                Connection conn = DBConnection.getConnection();

                String sql = "INSERT INTO chuyenbay VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement ps = conn.prepareStatement(sql);

                ps.setString(1, txtMaChuyenBay.getText());
                ps.setString(2, txtHHK.getText());
                ps.setString(3, txtDiemDen.getText());
                ps.setString(4, txtDiemDi.getText());
                ps.setString(5, txtNgayBay.getText());
                ps.setInt(6, Integer.parseInt(txtTongVe.getText()));
                ps.setInt(7, Integer.parseInt(txtDaBan.getText()));
                ps.setInt(8, Integer.parseInt(txtConLai.getText()));

                ps.executeUpdate();

                JOptionPane.showMessageDialog(frame, "Thêm thành công!");

                conn.close();
                frame.dispose();
                loadChuyenBay(); // reload bảng

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        });
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }                                         

    private void btnXoa_cbActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int selectedRow = tbl_cb.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một chuyến bay trên bảng để xóa!");
            return;
        }

        // Lấy mã chuyến bay từ cột 0 của dòng được chọn
        String maCB = tbl_cb.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa chuyến bay " + maCB + "?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            DAO.ChuyenBayDAO dao = new DAO.ChuyenBayDAO();
            if (dao.xoa(maCB)) { // Nhớ đổi tên hàm xoa() thành delete() nếu DAO của bạn dùng tiếng Anh
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                btnDoc_cbActionPerformed(evt); // Gọi hàm cập nhật lại bảng
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }                               

    private void btnThem_cbActionPerformed(java.awt.event.ActionEvent evt) {                                           
    // Tạo form với tiêu đề mới
    JFrame frame = new JFrame("Thêm Chuyến Bay mới");
    frame.setLayout(new GridLayout(0, 2, 10, 10)); // 2 cột, khoảng cách 10px
    frame.setSize(450, 650); // Tăng chiều cao lên 650 để đủ chỗ cho 12 dòng
    
    // Khởi tạo các ô nhập liệu (12 ô tương ứng với 12 thuộc tính)
    JTextField txtMaChuyenBay = new JTextField();
    JTextField txtMaMayBay = new JTextField();
    JTextField txtMaHangHangKhong = new JTextField();
    JTextField txtMaSanBayDi = new JTextField();
    JTextField txtMaSanBayDen = new JTextField();
    JTextField txtNgayBay = new JTextField();
    JTextField txtGioBay = new JTextField();
    JTextField txtGioDen = new JTextField();
    JTextField txtTongSoVe = new JTextField();
    JTextField txtSoVeDaBan = new JTextField(); 
    JTextField txtSoVeConLai = new JTextField();
    JTextField txtTienVeThuVe = new JTextField();
    
    // Thêm Label và TextField vào Form theo từng cặp
    frame.add(new JLabel("Mã Chuyến Bay:"));
    frame.add(txtMaChuyenBay);
    
    frame.add(new JLabel("Mã Máy Bay:"));
    frame.add(txtMaMayBay);
    
    frame.add(new JLabel("Mã Hãng Hàng Không:"));
    frame.add(txtMaHangHangKhong);
    
    frame.add(new JLabel("Mã Sân Bay Đi:"));
    frame.add(txtMaSanBayDi);
    
    frame.add(new JLabel("Mã Sân Bay Đến:"));
    frame.add(txtMaSanBayDen);
    
    frame.add(new JLabel("Ngày Bay (YYYY-MM-DD):"));
    frame.add(txtNgayBay);
    
    frame.add(new JLabel("Giờ Bay:"));
    frame.add(txtGioBay);
    
    frame.add(new JLabel("Giờ Đến:"));
    frame.add(txtGioDen);
    
    frame.add(new JLabel("Tổng Số Vé:"));
    frame.add(txtTongSoVe);
    
    frame.add(new JLabel("Số Vé Đã Bán:"));
    frame.add(txtSoVeDaBan);
    
    frame.add(new JLabel("Số Vé Còn Lại:"));
    frame.add(txtSoVeConLai);
    
    frame.add(new JLabel("Tiền Vé Thu Về:"));
    frame.add(txtTienVeThuVe);
    
    // Khởi tạo các nút bấm
    JButton btnSave = new JButton("💾 Lưu");
    JButton btnCancel = new JButton("❌ Hủy");
    
    JPanel buttonPanel = new JPanel();
    buttonPanel.add(btnSave);
    buttonPanel.add(btnCancel);
    
    frame.add(new JLabel()); // Ô trống để đẩy nút bấm sang cột bên phải
    frame.add(buttonPanel);
    
    // Xử lý sự kiện lưu
    btnSave.addActionListener(e -> {
    try {
        // Kiểm tra rỗng (Làm mẫu vài ô quan trọng)
        if (txtMaChuyenBay.getText().isEmpty() || txtNgayBay.getText().isEmpty()) {
            JOptionPane.showMessageDialog(frame, "Vui lòng nhập mã chuyến bay và ngày bay!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Gom dữ liệu từ các TextField
        model.ChuyenBay cb = new model.ChuyenBay();
        cb.setMaChuyenBay(txtMaChuyenBay.getText());
        cb.setMaHangHangKhong(txtHHK.getText());
        cb.setMaSanBayDen(txtDiemDen.getText());
        cb.setMaSanBayDi(txtDiemDi.getText());
        cb.setNgayBay(txtNgayBay.getText());
        
        // Ép kiểu cho các ô số
        cb.setTongSoVe(Integer.parseInt(txtTongVe.getText()));
        cb.setSoVeDaBan(Integer.parseInt(txtDaBan.getText()));
        
        // Gọi DAO để lưu vào CSDL
        DAO.ChuyenBayDAO dao = new DAO.ChuyenBayDAO();
        if (dao.them(cb)) { // Hoặc insert(cb)
            JOptionPane.showMessageDialog(frame, "Thêm chuyến bay thành công!");
            frame.dispose(); // Đóng cửa sổ nhập liệu
            btnDoc_cbActionPerformed(evt); // Cập nhật lại bảng chính
        } else {
            JOptionPane.showMessageDialog(frame, "Lỗi: Trùng mã chuyến bay hoặc sai dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(frame, "Lỗi: Tổng vé và Số vé đã bán phải là chữ số!", "Lỗi Nhập Liệu", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(frame, "Lỗi hệ thống: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
});
    
    // Xử lý sự kiện hủy
    btnCancel.addActionListener(e -> frame.dispose());
    
    // Hiển thị Form
    frame.setLocationRelativeTo(this);
    frame.setVisible(true);
}           
    
    
    //========================= SỰ KIỆN CHO QUẢN LÝ KHÁCH HÀNG ========================
    private void btnDoc_khActionPerformed(java.awt.event.ActionEvent evt) {                                          
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tbl_kh.getModel();
        model.setRowCount(0); 
        
        DAO.KhachHangDAO dao = new DAO.KhachHangDAO();
        java.util.ArrayList<model.KhachHang> list = dao.docTatCa();
        
        for (model.KhachHang kh : list) {
            model.addRow(new Object[]{
                kh.getMaKhachHang(), kh.getHo(), kh.getTen(), 
                null, // Cột Mã HHK trong bảng Khách Hàng của bạn đang bị dư, để null tạm
                kh.getNgaySinh(), kh.getSoDienThoai(), kh.getEmail()
            });
        }
    }
    private void btnThem_khActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        JFrame frame = new JFrame("Thêm Khách Hàng mới");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 500);
        
        JTextField txtMaKhachHang = new JTextField();
        JTextField txtHo = new JTextField();
        JTextField txtTen = new JTextField();
        JTextField txtMaHHK = new JTextField();
        JTextField txtNgaySinh = new JTextField();
        JTextField txtSDT = new JTextField();
        JTextField txtEmail = new JTextField();
        
        frame.add(new JLabel("Mã Khách Hàng:"));
        frame.add(txtMaKhachHang);
        frame.add(new JLabel("Họ:"));
        frame.add(txtHo);
        frame.add(new JLabel("Tên:"));
        frame.add(txtTen);
        frame.add(new JLabel("Mã Hãng Hàng Không:"));
        frame.add(txtMaHHK);
        frame.add(new JLabel("Ngày Sinh:"));
        frame.add(txtNgaySinh);
        frame.add(new JLabel("Số Điện Thoại:"));
        frame.add(txtSDT);
        frame.add(new JLabel("Email:"));
        frame.add(txtEmail);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    
    }                                          

    private void btnSua_khActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        JFrame frame = new JFrame("Sửa Thông Tin Khách Hàng ");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 400);
        
        JTextField txtMaKhachHang = new JTextField();
        JTextField txtHo = new JTextField();
        JTextField txtTen = new JTextField();
        JTextField txtMaHHK = new JTextField();
        JTextField txtNgaySinh = new JTextField();
        JTextField txtSDT = new JTextField();
        JTextField txtEmail = new JTextField();
        
        frame.add(new JLabel("Mã Khách Hàng:"));
        frame.add(txtMaKhachHang);
        frame.add(new JLabel("Họ:"));
        frame.add(txtHo);
        frame.add(new JLabel("Tên:"));
        frame.add(txtTen);
        frame.add(new JLabel("Mã Hãng Hàng Không:"));
        frame.add(txtMaHHK);
        frame.add(new JLabel("Ngày Sinh:"));
        frame.add(txtNgaySinh);
        frame.add(new JLabel("Số Điện Thoại:"));
        frame.add(txtSDT);
        frame.add(new JLabel("Email:"));
        frame.add(txtEmail);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    
    }                                         

    private void btnXoa_khActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnTim_khActionPerformed(java.awt.event.ActionEvent evt) {                                           
    String maKH = JOptionPane.showInputDialog(this, "Nhập mã khách hàng:");

    if (maKH != null && !maKH.trim().isEmpty()) {
        try {
            Connection conn = DBConnection.getConnection();

            String sql = "SELECT * FROM khachhang WHERE maKhachHang = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, maKH);

            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tbl_kh.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("maKhachHang"),  // sửa lại đúng tên
                    rs.getString("tenKhachHang"),
                    rs.getString("cccd"),
                    rs.getString("soDienThoai"),
                    rs.getString("email")
                });
            }

            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}                              
    
    
    //========================= SỰ KIỆN CHO QUẢN LÝ VÉ ========================
    private void btnThem_veActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        JFrame frame = new JFrame("Thêm Vé");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 300);
        
        JTextField txtMaChuyenBay = new JTextField();
        JTextField txtMaVe = new JTextField();
        JTextField txtMaGhe = new JTextField();
        JTextField txtLoaiVe= new JTextField();
        JTextField txtGiaVe= new JTextField();

        frame.add(new JLabel("Mã Vé:"));
        frame.add(txtMaVe);
        frame.add(new JLabel("Mã Chuyến Bay:"));
        frame.add(txtMaChuyenBay);
        frame.add(new JLabel("Mã Ghế:"));
        frame.add(txtMaGhe);
        frame.add(new JLabel("Lọai Vé:"));
        frame.add(txtLoaiVe);
        frame.add(new JLabel("Giá Vé:"));
        frame.add(txtGiaVe);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }                                          

    private void btnSua_veActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        JFrame frame = new JFrame("Sửa Vé");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 300);
        
        JTextField txtMaChuyenBay = new JTextField();
        JTextField txtMaVe = new JTextField();
        JTextField txtMaGhe = new JTextField();
        JTextField txtLoaiVe= new JTextField();
        JTextField txtGiaVe= new JTextField();

        frame.add(new JLabel("Mã Vé:"));
        frame.add(txtMaVe);
        frame.add(new JLabel("Mã Chuyến Bay:"));
        frame.add(txtMaChuyenBay);
        frame.add(new JLabel("Mã Ghế:"));
        frame.add(txtMaGhe);
        frame.add(new JLabel("Lọai Vé:"));
        frame.add(txtLoaiVe);
        frame.add(new JLabel("Giá Vé:"));
        frame.add(txtGiaVe);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }                                         
    
    private void btnXoa_veActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnTim_veActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String maVe = JOptionPane.showInputDialog(this, "Nhập mã vé:");

        if (maVe != null && !maVe.trim().isEmpty()) {
            try {
                Connection conn = DBConnection.getConnection();

                String sql = "SELECT * FROM ve WHERE maVe = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, maVe);

                ResultSet rs = ps.executeQuery();

                DefaultTableModel model = (DefaultTableModel) tbl_ve.getModel();
                model.setRowCount(0);

                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("maVe"),
                        rs.getString("maChuyenBay"),
                        rs.getString("maKH"),
                        rs.getString("giaVe"),
                        rs.getString("loaiVe")
                    });
                }

                conn.close();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }                                      
    
    
    //========================= SỰ KIỆN CHO QUẢN LÝ CTKM ========================
    private void btnThem_ctkmActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        JFrame frame = new JFrame("Thêm Chương Trình Khuyến Mãi");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 400);
        
        JTextField txtMaKhuyenMai = new JTextField();
        JTextField txtTen = new JTextField();
        JTextField txtGiaTri = new JTextField();
        JTextField txtNgayBatDau= new JTextField();
        JTextField txtNgayKetThuc= new JTextField();
        JTextField txtDieuKien= new JTextField();
        JTextField txtTrangThai= new JTextField();

        frame.add(new JLabel("Mã Khuyến Mãi:"));
        frame.add(txtMaKhuyenMai);
        frame.add(new JLabel("Tên Chương Trình Khuyến Mãi:"));
        frame.add(txtTen);
        frame.add(new JLabel("Giá Trị:"));
        frame.add(txtGiaTri);
        frame.add(new JLabel("Ngày Bắt Đầu:"));
        frame.add(txtNgayBatDau);
        frame.add(new JLabel("Ngày Kết Thúc:"));
        frame.add(txtNgayKetThuc);
        frame.add(new JLabel("Điều Kiện Áp Dụng:"));
        frame.add(txtDieuKien);
        frame.add(new JLabel("Trạng Thái:"));
        frame.add(txtTrangThai);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }                                            

    private void btnSua_ctkmActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        JFrame frame = new JFrame("Sửa Chương Trình Khuyến");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 400);
        
        JTextField txtMaKhuyenMai = new JTextField();
        JTextField txtTen = new JTextField();
        JTextField txtGiaTri = new JTextField();
        JTextField txtNgayBatDau= new JTextField();
        JTextField txtNgayKetThuc= new JTextField();
        JTextField txtDieuKien= new JTextField();
        JTextField txtTrangThai= new JTextField();

        frame.add(new JLabel("Mã Khuyến Mãi:"));
        frame.add(txtMaKhuyenMai);
        frame.add(new JLabel("Tên Chương Trình Khuyến Mãi:"));
        frame.add(txtTen);
        frame.add(new JLabel("Giá Trị:"));
        frame.add(txtGiaTri);
        frame.add(new JLabel("Ngày Bắt Đầu:"));
        frame.add(txtNgayBatDau);
        frame.add(new JLabel("Ngày Kết Thúc:"));
        frame.add(txtNgayKetThuc);
        frame.add(new JLabel("Điều Kiện Áp Dụng:"));
        frame.add(txtDieuKien);
        frame.add(new JLabel("Trạng Thái:"));
        frame.add(txtTrangThai);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }                                           

    private void btnXoa_ctkmActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void btnTim_ctkmActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String ma = JOptionPane.showInputDialog(this, "Nhập mã CTKM:");

        if (ma != null && !ma.trim().isEmpty()) {
            try {
                Connection conn = DBConnection.getConnection();

                String sql = "SELECT * FROM ctkm WHERE maCTKM = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, ma);

                ResultSet rs = ps.executeQuery();

                DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
                model.setRowCount(0);

                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("maCTKM"),
                        rs.getString("tenCTKM"),
                        rs.getString("ngayBD"),
                        rs.getString("ngayKT"),
                        rs.getString("noiDung")
                    });
                }

                conn.close();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }                  
    
   
    //========================= SỰ KIỆN CHO BÁO CÁO ========================
    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }
    

    public void loadChuyenBay() {
        DefaultTableModel model = (DefaultTableModel) tbl_cb.getModel();
        model.setRowCount(0); // xóa dữ liệu cũ

        try {
            Connection conn = DBConnection.getConnection();
            String sql = "SELECT * FROM chuyenbay";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("maChuyenBay"),
                    rs.getString("maMayBay"),
                    rs.getString("maHangHangKhong"),
                    rs.getString("maSanBayDi"),
                    rs.getString("maSanBayDen"),
                    rs.getString("NgayBay"),
                    rs.getString("GioBay"),
                    rs.getString("GioDen"),
                    rs.getInt("TongSoVe"),
                    rs.getInt("SoVeDaBan"),
                    rs.getInt("SoVeConLai"),
                    rs.getLong("TienVeThuVe")
                });
            }

            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void loadKhachHang() {
        DefaultTableModel model = (DefaultTableModel) tbl_kh.getModel();
        model.setRowCount(0);

        try {
            Connection conn = DBConnection.getConnection();
            String sql = "SELECT * FROM khachhang";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("maKhachHang"),
                    rs.getString("ho"),
                    rs.getString("ten"),
                    rs.getString("ngaySinh"),
                    rs.getString("soDienThoai"),
                    rs.getString("email")
                });
            }

            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void loadVe() {
        DefaultTableModel model = (DefaultTableModel) tbl_ve.getModel();
        model.setRowCount(0);

        try {
            Connection conn = DBConnection.getConnection();
            String sql = "SELECT * FROM ve";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("maVe"),
                    rs.getString("maChuyenBay"),
                    rs.getString("maGhe"),
                    rs.getString("giaVe"),
                    rs.getString("loaiVe")
                });
            }

            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadCTKM() {
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        model.setRowCount(0);

        try {
            Connection conn = DBConnection.getConnection();
            String sql = "SELECT * FROM ctkm";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("maCTKM"),
                    rs.getString("tenCTKM"),
                    rs.getString("ngayBD"),
                    rs.getString("ngayKT"),
                    rs.getString("noiDung")
                });
            }

            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnBaoCao;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnSua_cb;
    private javax.swing.JButton btnSua_ctkm;
    private javax.swing.JButton btnSua_kh;
    private javax.swing.JButton btnSua_ve;
    private javax.swing.JButton btnThem_cb;
    private javax.swing.JButton btnThem_ctkm;
    private javax.swing.JButton btnThem_kh;
    private javax.swing.JButton btnThem_ve;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTim_cb;
    private javax.swing.JButton btnTim_ctkm;
    private javax.swing.JButton btnTim_kh;
    private javax.swing.JButton btnTim_ve;
    private javax.swing.JButton btnXoa_cb;
    private javax.swing.JButton btnXoa_ctkm;
    private javax.swing.JButton btnXoa_kh;
    private javax.swing.JButton btnXoa_ve;
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbl_cb;
    private javax.swing.JTable tbl_kh;
    private javax.swing.JTable tbl_ve;
    // End of variables declaration                   
}
