package gui;

import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;


public class GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public GUI() {
        initComponents();
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnThem_cb = new javax.swing.JButton();
        btnXoa_cb = new javax.swing.JButton();
        btnTim_cb = new javax.swing.JButton();
        btnSua_cb = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cb = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnThem_kh = new javax.swing.JButton();
        btnXoa_kh = new javax.swing.JButton();
        btnTim_kh = new javax.swing.JButton();
        btnSua_kh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_kh = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnThem_ve = new javax.swing.JButton();
        btnXoa_ve = new javax.swing.JButton();
        btnTim_ve = new javax.swing.JButton();
        btnSua_ve = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_ve = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        btnThem_ctkm = new javax.swing.JButton();
        btnXoa_ctkm = new javax.swing.JButton();
        btnTim_ctkm = new javax.swing.JButton();
        btnSua_ctkm = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnThongKe = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnBaoCao = new javax.swing.JButton();
        btnXuatHoaDon = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("HỆ THỐNG QUẢN LÝ CHUYẾN BAY");
        jTextField1.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTextField1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        btnThem_cb.setText("Thêm");
        btnThem_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_cbActionPerformed(evt);
            }
        });

        btnXoa_cb.setText("Xóa");
        btnXoa_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_cbActionPerformed(evt);
            }
        });

        btnTim_cb.setText("Tìm Kiếm");
        btnTim_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim_cbActionPerformed(evt);
            }
        });

        btnSua_cb.setText("Sửa");
        btnSua_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_cbActionPerformed(evt);
            }
        });

        tbl_cb.setAutoCreateRowSorter(true);
        tbl_cb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Chuyến Bay", "Hãng Hàng Không", "Điểm Đến", "Điểm Đi", "Ngày Bay", "Tổng Vé", "Đã Bán", "Còn Lại"
            }
        ));
        tbl_cb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_cb.setDoubleBuffered(true);
        jScrollPane1.setViewportView(tbl_cb);
        if (tbl_cb.getColumnModel().getColumnCount() > 0) {
            tbl_cb.getColumnModel().getColumn(5).setResizable(false);
            tbl_cb.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnThem_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnXoa_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSua_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnTim_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem_cb)
                    .addComponent(btnXoa_cb)
                    .addComponent(btnTim_cb)
                    .addComponent(btnSua_cb))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Quản Lý Chuyến Bay", jPanel7);

        btnThem_kh.setText("Thêm");
        btnThem_kh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_khActionPerformed(evt);
            }
        });

        btnXoa_kh.setText("Xóa");
        btnXoa_kh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_khActionPerformed(evt);
            }
        });

        btnTim_kh.setText("Tìm Kiếm");
        btnTim_kh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim_khActionPerformed(evt);
            }
        });

        btnSua_kh.setText("Sửa");
        btnSua_kh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_khActionPerformed(evt);
            }
        });

        tbl_kh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Họ", "Tên", "Mã Hãng Hàng Không", "Ngày Sinh", "SDT", "Email"
            }
        ));
        jScrollPane2.setViewportView(tbl_kh);
        if (tbl_kh.getColumnModel().getColumnCount() > 0) {
            tbl_kh.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnThem_kh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnXoa_kh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSua_kh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnTim_kh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem_kh)
                    .addComponent(btnXoa_kh)
                    .addComponent(btnTim_kh)
                    .addComponent(btnSua_kh))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Quản Lý Khách Hàng", jPanel8);

        btnThem_ve.setText("Thêm");
        btnThem_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_veActionPerformed(evt);
            }
        });

        btnXoa_ve.setText("Xóa");
        btnXoa_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_veActionPerformed(evt);
            }
        });

        btnTim_ve.setText("Tìm Kiếm");
        btnTim_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim_veActionPerformed(evt);
            }
        });

        btnSua_ve.setText("Sửa");
        btnSua_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_veActionPerformed(evt);
            }
        });

        tbl_ve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Vé", "Mã Chuyến Bay", "Mã Ghế", "Loại Vé", "Giá Vé"
            }
        ));
        jScrollPane3.setViewportView(tbl_ve);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnThem_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnXoa_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSua_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnTim_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem_ve)
                    .addComponent(btnXoa_ve)
                    .addComponent(btnTim_ve)
                    .addComponent(btnSua_ve))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Quản Lý Vé", jPanel10);

        btnThem_ctkm.setText("Thêm");
        btnThem_ctkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_ctkmActionPerformed(evt);
            }
        });

        btnXoa_ctkm.setText("Xóa");
        btnXoa_ctkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_ctkmActionPerformed(evt);
            }
        });

        btnTim_ctkm.setText("Tìm Kiếm");
        btnTim_ctkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim_ctkmActionPerformed(evt);
            }
        });

        btnSua_ctkm.setText("Sửa");
        btnSua_ctkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_ctkmActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khuyến Mãi", "Tên", "Giá Trị", "Ngày bắt đầu", "Ngày kết thúc", "Điều Kiện Áp Dụng", "Trạng Thái"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnThem_ctkm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnXoa_ctkm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSua_ctkm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnTim_ctkm, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem_ctkm)
                    .addComponent(btnXoa_ctkm)
                    .addComponent(btnTim_ctkm)
                    .addComponent(btnSua_ctkm))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Quản Lý CTKM", jPanel12);

        btnThongKe.setText("Thống Kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnHoaDon.setText("Xem Hóa Đơn");
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        btnBaoCao.setText("Báo Cáo");
        btnBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaoCaoActionPerformed(evt);
            }
        });

        btnXuatHoaDon.setText("Xuất Hóa Đơn");
        btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHoaDonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane6.addTab("Báo Cáo", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    
    // ========================= SỰ KIỆN CHO QUẢN LÝ CHUYẾN BAY ========================
    private void btnTim_cbActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:     
        String maCB = JOptionPane.showInputDialog(this, "Nhập mã Chuyến Bay:");
        if (maCB != null && !maCB.trim().isEmpty()) {
            String cb="";
            if (cb != null) {
                System.out.println("=== THÔNG TIN CHUYẾN BAY ===");
            } else {
                System.out.println("Không tìm thấy sinh viên với mã: " + maCB);
            }
        }
    }                                         

    private void btnSua_cbActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        JFrame frame = new JFrame("Sửa Thông Tin Chuyến Bay ");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 500);
        
        JTextField txtMaChuyenBay = new JTextField();
        JTextField txtHHK = new JTextField();
        JTextField txtDiemDen = new JTextField();
        JTextField txtDiemDi= new JTextField();
        JTextField txtNgayBay= new JTextField();
        JTextField txtTongVe = new JTextField();
        JTextField txtDaBan = new JTextField();
        JTextField txtConLai = new JTextField();
        
        frame.add(new JLabel("Mã Chuyến Bay:"));
        frame.add(txtMaChuyenBay);
        frame.add(new JLabel("Hãng Hàng Không:"));
        frame.add(txtHHK);
        frame.add(new JLabel("Điểm Đến:"));
        frame.add(txtDiemDen);
        frame.add(new JLabel("Điểm Đi:"));
        frame.add(txtDiemDi);
        frame.add(new JLabel("Ngày Bay:"));
        frame.add(txtNgayBay);
        frame.add(new JLabel("Tổng Vé:"));
        frame.add(txtTongVe);
        frame.add(new JLabel("Đã Bán:"));
        frame.add(txtDaBan);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }                                         

    private void btnXoa_cbActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnThem_cbActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        JFrame frame = new JFrame("Thêm Chuyến Bay mới");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 500);
        
        JTextField txtMaChuyenBay = new JTextField();
        JTextField txtHHK = new JTextField();
        JTextField txtDiemDen = new JTextField();
        JTextField txtDiemDi= new JTextField();
        JTextField txtNgayBay= new JTextField();
        JTextField txtTongVe = new JTextField();
        JTextField txtDaBan = new JTextField();
        JTextField txtConLai = new JTextField();
        
        frame.add(new JLabel("Mã Chuyến Bay:"));
        frame.add(txtMaChuyenBay);
        frame.add(new JLabel("Hãng Hàng Không:"));
        frame.add(txtHHK);
        frame.add(new JLabel("Điểm Đến:"));
        frame.add(txtDiemDen);
        frame.add(new JLabel("Điểm Đi:"));
        frame.add(txtDiemDi);
        frame.add(new JLabel("Ngày Bay:"));
        frame.add(txtNgayBay);
        frame.add(new JLabel("Tổng Vé:"));
        frame.add(txtTongVe);
        frame.add(new JLabel("Đã Bán:"));
        frame.add(txtDaBan);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }                                          
    
    
    //========================= SỰ KIỆN CHO QUẢN LÝ KHÁCH HÀNG ========================
    private void btnThem_khActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        JFrame frame = new JFrame("Thêm Khách Hàng mới");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 500);
        
        JTextField txtMaKhachHang = new JTextField();
        JTextField txtHo = new JTextField();
        JTextField txtTen = new JTextField();
        JTextField txtMaHHK = new JTextField();
        JTextField txtNgaySinh = new JTextField();
        JTextField txtSDT = new JTextField();
        JTextField txtEmail = new JTextField();
        
        frame.add(new JLabel("Mã Khách Hàng:"));
        frame.add(txtMaKhachHang);
        frame.add(new JLabel("Họ:"));
        frame.add(txtHo);
        frame.add(new JLabel("Tên:"));
        frame.add(txtTen);
        frame.add(new JLabel("Mã Hãng Hàng Không:"));
        frame.add(txtMaHHK);
        frame.add(new JLabel("Ngày Sinh:"));
        frame.add(txtNgaySinh);
        frame.add(new JLabel("Số Điện Thoại:"));
        frame.add(txtSDT);
        frame.add(new JLabel("Email:"));
        frame.add(txtEmail);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    
    }                                          

    private void btnSua_khActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        JFrame frame = new JFrame("Sửa Thông Tin Khách Hàng ");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 400);
        
        JTextField txtMaKhachHang = new JTextField();
        JTextField txtHo = new JTextField();
        JTextField txtTen = new JTextField();
        JTextField txtMaHHK = new JTextField();
        JTextField txtNgaySinh = new JTextField();
        JTextField txtSDT = new JTextField();
        JTextField txtEmail = new JTextField();
        
        frame.add(new JLabel("Mã Khách Hàng:"));
        frame.add(txtMaKhachHang);
        frame.add(new JLabel("Họ:"));
        frame.add(txtHo);
        frame.add(new JLabel("Tên:"));
        frame.add(txtTen);
        frame.add(new JLabel("Mã Hãng Hàng Không:"));
        frame.add(txtMaHHK);
        frame.add(new JLabel("Ngày Sinh:"));
        frame.add(txtNgaySinh);
        frame.add(new JLabel("Số Điện Thoại:"));
        frame.add(txtSDT);
        frame.add(new JLabel("Email:"));
        frame.add(txtEmail);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    
    }                                         

    private void btnXoa_khActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnTim_khActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String maKH = JOptionPane.showInputDialog(this, "Nhập mã Khách Hàng:");
        if (maKH != null && !maKH.trim().isEmpty()) {
            String kh="";
            if (kh != null) {
                System.out.println("=== THÔNG TIN KHÁCH HÀNG ===");
            } else {
                System.out.println("Không tìm thấy sinh viên với mã: " + maKH);
            }
        }
    }                                         
    
    
    //========================= SỰ KIỆN CHO QUẢN LÝ VÉ ========================
    private void btnThem_veActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        JFrame frame = new JFrame("Thêm Vé");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 300);
        
        JTextField txtMaChuyenBay = new JTextField();
        JTextField txtMaVe = new JTextField();
        JTextField txtMaGhe = new JTextField();
        JTextField txtLoaiVe= new JTextField();
        JTextField txtGiaVe= new JTextField();

        frame.add(new JLabel("Mã Vé:"));
        frame.add(txtMaVe);
        frame.add(new JLabel("Mã Chuyến Bay:"));
        frame.add(txtMaChuyenBay);
        frame.add(new JLabel("Mã Ghế:"));
        frame.add(txtMaGhe);
        frame.add(new JLabel("Lọai Vé:"));
        frame.add(txtLoaiVe);
        frame.add(new JLabel("Giá Vé:"));
        frame.add(txtGiaVe);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }                                          

    private void btnSua_veActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        JFrame frame = new JFrame("Sửa Vé");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 300);
        
        JTextField txtMaChuyenBay = new JTextField();
        JTextField txtMaVe = new JTextField();
        JTextField txtMaGhe = new JTextField();
        JTextField txtLoaiVe= new JTextField();
        JTextField txtGiaVe= new JTextField();

        frame.add(new JLabel("Mã Vé:"));
        frame.add(txtMaVe);
        frame.add(new JLabel("Mã Chuyến Bay:"));
        frame.add(txtMaChuyenBay);
        frame.add(new JLabel("Mã Ghế:"));
        frame.add(txtMaGhe);
        frame.add(new JLabel("Lọai Vé:"));
        frame.add(txtLoaiVe);
        frame.add(new JLabel("Giá Vé:"));
        frame.add(txtGiaVe);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }                                         
    
    private void btnXoa_veActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnTim_veActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
                String maVe = JOptionPane.showInputDialog(this, "Nhập mã Vé:");
        if (maVe != null && !maVe.trim().isEmpty()) {
            String ve="";
            if (ve != null) {
                System.out.println("=== THÔNG TIN KHÁCH HÀNG ===");
            } else {
                System.out.println("Không tìm thấy sinh viên với mã: " + maVe);
            }
        }
    }                                         
    
    
    //========================= SỰ KIỆN CHO QUẢN LÝ CTKM ========================
    private void btnThem_ctkmActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        JFrame frame = new JFrame("Thêm Chương Trình Khuyến Mãi");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 400);
        
        JTextField txtMaKhuyenMai = new JTextField();
        JTextField txtTen = new JTextField();
        JTextField txtGiaTri = new JTextField();
        JTextField txtNgayBatDau= new JTextField();
        JTextField txtNgayKetThuc= new JTextField();
        JTextField txtDieuKien= new JTextField();
        JTextField txtTrangThai= new JTextField();

        frame.add(new JLabel("Mã Khuyến Mãi:"));
        frame.add(txtMaKhuyenMai);
        frame.add(new JLabel("Tên Chương Trình Khuyến Mãi:"));
        frame.add(txtTen);
        frame.add(new JLabel("Giá Trị:"));
        frame.add(txtGiaTri);
        frame.add(new JLabel("Ngày Bắt Đầu:"));
        frame.add(txtNgayBatDau);
        frame.add(new JLabel("Ngày Kết Thúc:"));
        frame.add(txtNgayKetThuc);
        frame.add(new JLabel("Điều Kiện Áp Dụng:"));
        frame.add(txtDieuKien);
        frame.add(new JLabel("Trạng Thái:"));
        frame.add(txtTrangThai);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }                                            

    private void btnSua_ctkmActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        JFrame frame = new JFrame("Sửa Chương Trình Khuyến");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 400);
        
        JTextField txtMaKhuyenMai = new JTextField();
        JTextField txtTen = new JTextField();
        JTextField txtGiaTri = new JTextField();
        JTextField txtNgayBatDau= new JTextField();
        JTextField txtNgayKetThuc= new JTextField();
        JTextField txtDieuKien= new JTextField();
        JTextField txtTrangThai= new JTextField();

        frame.add(new JLabel("Mã Khuyến Mãi:"));
        frame.add(txtMaKhuyenMai);
        frame.add(new JLabel("Tên Chương Trình Khuyến Mãi:"));
        frame.add(txtTen);
        frame.add(new JLabel("Giá Trị:"));
        frame.add(txtGiaTri);
        frame.add(new JLabel("Ngày Bắt Đầu:"));
        frame.add(txtNgayBatDau);
        frame.add(new JLabel("Ngày Kết Thúc:"));
        frame.add(txtNgayKetThuc);
        frame.add(new JLabel("Điều Kiện Áp Dụng:"));
        frame.add(txtDieuKien);
        frame.add(new JLabel("Trạng Thái:"));
        frame.add(txtTrangThai);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }                                           

    private void btnXoa_ctkmActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void btnTim_ctkmActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
                String maCTKM= JOptionPane.showInputDialog(this, "Nhập mã CTKM:");
        if (maCTKM != null && !maCTKM.trim().isEmpty()) {
            String ctkm="";
            if (ctkm != null) {
                System.out.println("=== THÔNG TIN KHÁCH HÀNG ===");
            } else {
                System.out.println("Không tìm thấy sinh viên với mã: " + maCTKM);
            }
        }
    }                                           
    
   
    //========================= SỰ KIỆN CHO BÁO CÁO ========================
    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnBaoCao;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnSua_cb;
    private javax.swing.JButton btnSua_ctkm;
    private javax.swing.JButton btnSua_kh;
    private javax.swing.JButton btnSua_ve;
    private javax.swing.JButton btnThem_cb;
    private javax.swing.JButton btnThem_ctkm;
    private javax.swing.JButton btnThem_kh;
    private javax.swing.JButton btnThem_ve;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTim_cb;
    private javax.swing.JButton btnTim_ctkm;
    private javax.swing.JButton btnTim_kh;
    private javax.swing.JButton btnTim_ve;
    private javax.swing.JButton btnXoa_cb;
    private javax.swing.JButton btnXoa_ctkm;
    private javax.swing.JButton btnXoa_kh;
    private javax.swing.JButton btnXoa_ve;
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbl_cb;
    private javax.swing.JTable tbl_kh;
    private javax.swing.JTable tbl_ve;
    // End of variables declaration                   
}
