package gui;

import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import database.DBConnection;


public class GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public GUI() {
        initComponents();
        loadChuyenBay();
        loadKhachHang();
        loadVe();
        jTabbedPane6.addChangeListener(e -> {
            int index = jTabbedPane6.getSelectedIndex();

            if (index == 0) {
                loadChuyenBay();
            } else if (index == 1) {
                loadKhachHang();
            } else if (index == 2) {
                loadVe();
            } else if (index == 3) {
                loadCTKM();
            }
        });
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnThem_cb = new javax.swing.JButton();
        btnXoa_cb = new javax.swing.JButton();
        btnTim_cb = new javax.swing.JButton();
        btnSua_cb = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cb = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnThem_kh = new javax.swing.JButton();
        btnXoa_kh = new javax.swing.JButton();
        btnTim_kh = new javax.swing.JButton();
        btnSua_kh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_kh = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnThem_ve = new javax.swing.JButton();
        btnXoa_ve = new javax.swing.JButton();
        btnTim_ve = new javax.swing.JButton();
        btnSua_ve = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_ve = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        btnThem_ctkm = new javax.swing.JButton();
        btnXoa_ctkm = new javax.swing.JButton();
        btnTim_ctkm = new javax.swing.JButton();
        btnSua_ctkm = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnThongKe = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnBaoCao = new javax.swing.JButton();
        btnXuatHoaDon = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("HỆ THỐNG QUẢN LÝ CHUYẾN BAY");
        jTextField1.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTextField1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        btnThem_cb.setText("Thêm");
        btnThem_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_cbActionPerformed(evt);
            }
        });

        btnXoa_cb.setText("Xóa");
        btnXoa_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_cbActionPerformed(evt);
            }
        });

        btnTim_cb.setText("Tìm Kiếm");
        btnTim_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim_cbActionPerformed(evt);
            }
        });

        btnSua_cb.setText("Sửa");
        btnSua_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_cbActionPerformed(evt);
            }
        });

        javax.swing.JButton btnDoc_cb = new javax.swing.JButton("Cập Nhật");
        btnDoc_cb.addActionListener(e -> btnDoc_cbActionPerformed(e));

        jPanel4.setLayout(new java.awt.BorderLayout(0, 15)); 

        tbl_cb.setAutoCreateRowSorter(true);
        tbl_cb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã CB", "Mã Máy Bay", "Mã HHK", "Nơi Đi", "Nơi Đến", 
                "Ngày Bay", "Giờ Bay", "Giờ Đến", "Tổng Vé", "Đã Bán", "Còn Lại", "Tiền Vé"
            }
        ));
        tbl_cb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_cb.setDoubleBuffered(true);
        jScrollPane1.setViewportView(tbl_cb);
        if (tbl_cb.getColumnModel().getColumnCount() > 0) {
            tbl_cb.getColumnModel().getColumn(5).setResizable(false);
            tbl_cb.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(new java.awt.BorderLayout(0, 15));

        //Panel mới chứa toàn bộ các nút bấm
        javax.swing.JPanel buttonPanelCB = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));
        
        buttonPanelCB.add(btnThem_cb);
        buttonPanelCB.add(btnXoa_cb);
        buttonPanelCB.add(btnSua_cb);
        buttonPanelCB.add(btnTim_cb);
        buttonPanelCB.add(btnDoc_cb);

        // 3. KHAI BÁO VÀ THÊM 2 NÚT EXCEL MỚI TINH VÀO ĐÂY
        javax.swing.JButton btnXuatExcel_cb = new javax.swing.JButton("Xuất Excel");
        javax.swing.JButton btnNhapExcel_cb = new javax.swing.JButton("Nhập Excel");
        buttonPanelCB.add(btnXuatExcel_cb);
        buttonPanelCB.add(btnNhapExcel_cb);

        // 4. Gắn sự kiện (Click) cho 2 nút mới
        btnXuatExcel_cb.addActionListener(e -> btnXuatExcel_cbActionPerformed(e));
        btnNhapExcel_cb.addActionListener(e -> btnNhapExcel_cbActionPerformed(e));

        // 5. Gắn Panel nút bấm lên TỰA ĐẦU (NORTH) và Bảng dữ liệu vào GIỮA (CENTER)
        jPanel4.add(buttonPanelCB, java.awt.BorderLayout.NORTH);
        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        // --- KẾT THÚC ĐOẠN CODE MỚI ---

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Quản Lý Chuyến Bay", jPanel7);

        btnThem_kh.setText("Thêm");
        btnThem_kh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_khActionPerformed(evt);
            }
        });

        btnXoa_kh.setText("Xóa");
        btnXoa_kh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_khActionPerformed(evt);
            }
        });

        btnTim_kh.setText("Tìm Kiếm");
        btnTim_kh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim_khActionPerformed(evt);
            }
        });

        btnSua_kh.setText("Sửa");
        btnSua_kh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_khActionPerformed(evt);
            }
        });

        tbl_kh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Họ", "Tên", "Mã Hãng Hàng Không", "Ngày Sinh", "SDT", "Email"
            }
        ));
        jScrollPane2.setViewportView(tbl_kh);
        if (tbl_kh.getColumnModel().getColumnCount() > 0) {
            tbl_kh.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnThem_kh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnXoa_kh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSua_kh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnTim_kh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem_kh)
                    .addComponent(btnXoa_kh)
                    .addComponent(btnTim_kh)
                    .addComponent(btnSua_kh))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Quản Lý Khách Hàng", jPanel8);

        btnThem_ve.setText("Thêm");
        btnThem_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_veActionPerformed(evt);
            }
        });

        btnXoa_ve.setText("Xóa");
        btnXoa_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_veActionPerformed(evt);
            }
        });

        btnTim_ve.setText("Tìm Kiếm");
        btnTim_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim_veActionPerformed(evt);
            }
        });

        btnSua_ve.setText("Sửa");
        btnSua_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_veActionPerformed(evt);
            }
        });

        tbl_ve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Vé", "Mã Chuyến Bay", "Mã Ghế", "Loại Vé", "Giá Vé"
            }
        ));
        jScrollPane3.setViewportView(tbl_ve);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnThem_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnXoa_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSua_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnTim_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem_ve)
                    .addComponent(btnXoa_ve)
                    .addComponent(btnTim_ve)
                    .addComponent(btnSua_ve))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Quản Lý Vé", jPanel10);

        btnThem_ctkm.setText("Thêm");
        btnThem_ctkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_ctkmActionPerformed(evt);
            }
        });

        btnXoa_ctkm.setText("Xóa");
        btnXoa_ctkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_ctkmActionPerformed(evt);
            }
        });

        btnTim_ctkm.setText("Tìm Kiếm");
        btnTim_ctkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim_ctkmActionPerformed(evt);
            }
        });

        btnSua_ctkm.setText("Sửa");
        btnSua_ctkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_ctkmActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khuyến Mãi", "Tên", "Giá Trị", "Ngày bắt đầu", "Ngày kết thúc", "Điều Kiện Áp Dụng", "Trạng Thái"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnThem_ctkm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnXoa_ctkm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSua_ctkm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnTim_ctkm, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem_ctkm)
                    .addComponent(btnXoa_ctkm)
                    .addComponent(btnTim_ctkm)
                    .addComponent(btnSua_ctkm))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Quản Lý CTKM", jPanel12);

        btnThongKe.setText("Thống Kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnHoaDon.setText("Xem Hóa Đơn");
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        btnBaoCao.setText("Báo Cáo");
        btnBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaoCaoActionPerformed(evt);
            }
        });

        btnXuatHoaDon.setText("Xuất Hóa Đơn");
        btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHoaDonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane6.addTab("Báo Cáo", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane6)
                .addContainerGap())
        );

        pack();
    }              

    
    // ========================= SỰ KIỆN CHO QUẢN LÝ CHUYẾN BAY ========================
    private void btnDoc_cbActionPerformed(java.awt.event.ActionEvent evt) {                                          

    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tbl_cb.getModel();
    model.setRowCount(0); // Xóa sạch dữ liệu cũ trên bảng
    
    DAO.ChuyenBayDAO dao = new DAO.ChuyenBayDAO();
    java.util.ArrayList<DAL.ChuyenBay> list = dao.docTatCa();
    
    // Dữ liệu mới
    for (DAL.ChuyenBay cb : list) {
        model.addRow(new Object[]{
            cb.getMaChuyenBay(), cb.getMaMayBay(), cb.getMaHangHangKhong(),
            cb.getMaSanBayDi(), cb.getMaSanBayDen(), cb.getNgayBay(),
            cb.getGioBay(), cb.getGioDen(), cb.getTongSoVe(),
            cb.getSoVeDaBan(), cb.getSoVeConLai(), cb.getTienVeThuVe()
        });
    }
}
    private void btnTim_cbActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String maCB = JOptionPane.showInputDialog(this, "Nhập mã Chuyến Bay:");

        if (maCB != null && !maCB.trim().isEmpty()) {
            try {
                Connection conn = DBConnection.getConnection();

                String sql = "SELECT * FROM chuyenbay WHERE maCB = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, maCB);

                ResultSet rs = ps.executeQuery();

                DefaultTableModel model = (DefaultTableModel) tbl_cb.getModel();
                model.setRowCount(0);

                if (rs.next()) {
                    model.addRow(new Object[]{
                    rs.getString("maChuyenBay"),
                    rs.getString("maMayBay"),
                    rs.getString("maHangHangKhong"),
                    rs.getString("maSanBayDi"),
                    rs.getString("maSanBayDen"),
                    rs.getString("NgayBay"),
                    rs.getString("GioBay"),
                    rs.getString("GioDen"),
                    rs.getInt("TongSoVe"),
                    rs.getInt("SoVeDaBan"),
                    rs.getInt("SoVeConLai"),
                    rs.getLong("TienVeThuVe")
                    });
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy!");
                }

                conn.close();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    private void btnSua_cbActionPerformed(java.awt.event.ActionEvent evt) {                                                                                 
        // 1. Kiểm tra xem người dùng đã chọn dòng nào
        int selectedRow = tbl_cb.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một chuyến bay trên bảng để sửa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Tạo Form Sửa
        JFrame frame = new JFrame("Sửa Thông Tin Chuyến Bay");
        frame.setLayout(new java.awt.GridLayout(0, 2, 10, 10));
        frame.setSize(450, 650);
        
        JTextField txtMaChuyenBay = new JTextField();
        JTextField txtMaMayBay = new JTextField();
        JTextField txtMaHangHangKhong = new JTextField();
        JTextField txtMaSanBayDi = new JTextField();
        JTextField txtMaSanBayDen = new JTextField();
        JTextField txtNgayBay = new JTextField();
        JTextField txtGioBay = new JTextField();
        JTextField txtGioDen = new JTextField();
        JTextField txtTongSoVe = new JTextField();
        JTextField txtSoVeDaBan = new JTextField();
        JTextField txtSoVeConLai = new JTextField();
        JTextField txtTienVeThuVe = new JTextField();

        // 3. Lấy dữ liệu từ dòng đang chọn
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tbl_cb.getModel();
        
        txtMaChuyenBay.setText(model.getValueAt(selectedRow, 0) != null ? model.getValueAt(selectedRow, 0).toString() : "");
        txtMaChuyenBay.setEditable(false);

        txtMaMayBay.setText(model.getValueAt(selectedRow, 1) != null ? model.getValueAt(selectedRow, 1).toString() : "");
        txtMaHangHangKhong.setText(model.getValueAt(selectedRow, 2) != null ? model.getValueAt(selectedRow, 2).toString() : "");
        txtMaSanBayDi.setText(model.getValueAt(selectedRow, 3) != null ? model.getValueAt(selectedRow, 3).toString() : "");
        txtMaSanBayDen.setText(model.getValueAt(selectedRow, 4) != null ? model.getValueAt(selectedRow, 4).toString() : "");
        txtNgayBay.setText(model.getValueAt(selectedRow, 5) != null ? model.getValueAt(selectedRow, 5).toString() : "");
        txtGioBay.setText(model.getValueAt(selectedRow, 6) != null ? model.getValueAt(selectedRow, 6).toString() : "");
        txtGioDen.setText(model.getValueAt(selectedRow, 7) != null ? model.getValueAt(selectedRow, 7).toString() : "");
        txtTongSoVe.setText(model.getValueAt(selectedRow, 8) != null ? model.getValueAt(selectedRow, 8).toString() : "0");
        txtSoVeDaBan.setText(model.getValueAt(selectedRow, 9) != null ? model.getValueAt(selectedRow, 9).toString() : "0");
        txtSoVeConLai.setText(model.getValueAt(selectedRow, 10) != null ? model.getValueAt(selectedRow, 10).toString() : "0");
        txtTienVeThuVe.setText(model.getValueAt(selectedRow, 11) != null ? model.getValueAt(selectedRow, 11).toString() : "0");

        // 4. Gắn Label và TextField
        frame.add(new JLabel("Mã Chuyến Bay (Khóa):")); frame.add(txtMaChuyenBay);
        frame.add(new JLabel("Mã Máy Bay:")); frame.add(txtMaMayBay);
        frame.add(new JLabel("Mã Hãng Hàng Không:")); frame.add(txtMaHangHangKhong);
        frame.add(new JLabel("Mã Sân Bay Đi:")); frame.add(txtMaSanBayDi);
        frame.add(new JLabel("Mã Sân Bay Đến:")); frame.add(txtMaSanBayDen);
        frame.add(new JLabel("Ngày Bay (YYYY-MM-DD):")); frame.add(txtNgayBay);
        frame.add(new JLabel("Giờ Bay:")); frame.add(txtGioBay);
        frame.add(new JLabel("Giờ Đến:")); frame.add(txtGioDen);
        frame.add(new JLabel("Tổng Số Vé:")); frame.add(txtTongSoVe);
        frame.add(new JLabel("Số Vé Đã Bán:")); frame.add(txtSoVeDaBan);
        frame.add(new JLabel("Số Vé Còn Lại:")); frame.add(txtSoVeConLai);
        frame.add(new JLabel("Tiền Vé Thu Về:")); frame.add(txtTienVeThuVe);
        
        JButton btnSave = new JButton("💾 Cập Nhật");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        // 5. bấm nút Cập Nhật
        btnSave.addActionListener(e -> {
            try {
                // Kết nối Database và dùng lệnh UPDATE
                Connection conn = DBConnection.getConnection();
                String sql = "UPDATE chuyenbay SET maMayBay=?, maHangHangKhong=?, maSanBayDi=?, maSanBayDen=?, NgayBay=?, GioBay=?, GioDen=?, TongSoVe=?, SoVeDaBan=?, SoVeConLai=?, TienVeThuVe=? WHERE maChuyenBay=?";
                PreparedStatement ps = conn.prepareStatement(sql);

                ps.setString(1, txtMaMayBay.getText().trim());
                ps.setString(2, txtMaHangHangKhong.getText().trim());
                ps.setString(3, txtMaSanBayDi.getText().trim());
                ps.setString(4, txtMaSanBayDen.getText().trim());
                ps.setString(5, txtNgayBay.getText().trim());
                ps.setString(6, txtGioBay.getText().trim());
                ps.setString(7, txtGioDen.getText().trim());
                
                // Ép kiểu
                ps.setInt(8, Integer.parseInt(txtTongSoVe.getText().trim().isEmpty() ? "0" : txtTongSoVe.getText().trim()));
                ps.setInt(9, Integer.parseInt(txtSoVeDaBan.getText().trim().isEmpty() ? "0" : txtSoVeDaBan.getText().trim()));
                ps.setInt(10, Integer.parseInt(txtSoVeConLai.getText().trim().isEmpty() ? "0" : txtSoVeConLai.getText().trim()));
                ps.setLong(11, Long.parseLong(txtTienVeThuVe.getText().trim().isEmpty() ? "0" : txtTienVeThuVe.getText().trim()));
                
                // Điều kiện
                ps.setString(12, txtMaChuyenBay.getText().trim());

                int rowsUpdated = ps.executeUpdate();

                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(frame, "Cập nhật chuyến bay thành công!");
                    frame.dispose();
                    btnDoc_cbActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(frame, "Cập nhật thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }

                conn.close();

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(frame, "Lỗi nhập liệu: Tổng vé, Số vé, Tiền vé phải là số nguyên!", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(frame, "Lỗi hệ thống: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        });
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }           

    private void btnXoa_cbActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int selectedRow = tbl_cb.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một chuyến bay trên bảng để xóa!");
            return;
        }

        // Lấy mã chuyến bay
        String maCB = tbl_cb.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa chuyến bay " + maCB + "?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            DAO.ChuyenBayDAO dao = new DAO.ChuyenBayDAO();
            if (dao.xoa(maCB)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                btnDoc_cbActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }                               

    private void btnThem_cbActionPerformed(java.awt.event.ActionEvent evt) {                                           
    // Tạo form mới
    JFrame frame = new JFrame("Thêm Chuyến Bay mới");
    frame.setLayout(new GridLayout(0, 2, 10, 10));
    frame.setSize(450, 650);
    
    // Khởi tạo các ô nhập liệu
    JTextField txtMaChuyenBay = new JTextField();
    JTextField txtMaMayBay = new JTextField();
    JTextField txtMaHangHangKhong = new JTextField();
    JTextField txtMaSanBayDi = new JTextField();
    JTextField txtMaSanBayDen = new JTextField();
    JTextField txtNgayBay = new JTextField();
    JTextField txtGioBay = new JTextField();
    JTextField txtGioDen = new JTextField();
    JTextField txtTongSoVe = new JTextField();
    JTextField txtSoVeDaBan = new JTextField(); 
    JTextField txtSoVeConLai = new JTextField();
    JTextField txtTienVeThuVe = new JTextField();
    
    // Thêm Label và TextField
    frame.add(new JLabel("Mã Chuyến Bay:"));
    frame.add(txtMaChuyenBay);
    
    frame.add(new JLabel("Mã Máy Bay:"));
    frame.add(txtMaMayBay);
    
    frame.add(new JLabel("Mã Hãng Hàng Không:"));
    frame.add(txtMaHangHangKhong);
    
    frame.add(new JLabel("Mã Sân Bay Đi:"));
    frame.add(txtMaSanBayDi);
    
    frame.add(new JLabel("Mã Sân Bay Đến:"));
    frame.add(txtMaSanBayDen);
    
    frame.add(new JLabel("Ngày Bay (YYYY-MM-DD):"));
    frame.add(txtNgayBay);
    
    frame.add(new JLabel("Giờ Bay:"));
    frame.add(txtGioBay);
    
    frame.add(new JLabel("Giờ Đến:"));
    frame.add(txtGioDen);
    
    frame.add(new JLabel("Tổng Số Vé:"));
    frame.add(txtTongSoVe);
    
    frame.add(new JLabel("Số Vé Đã Bán:"));
    frame.add(txtSoVeDaBan);
    
    frame.add(new JLabel("Số Vé Còn Lại:"));
    frame.add(txtSoVeConLai);
    
    frame.add(new JLabel("Tiền Vé Thu Về:"));
    frame.add(txtTienVeThuVe);
    
    // Khởi tạo các nút
    JButton btnSave = new JButton("💾 Lưu");
    JButton btnCancel = new JButton("❌ Hủy");
    
    JPanel buttonPanel = new JPanel();
    buttonPanel.add(btnSave);
    buttonPanel.add(btnCancel);
    
    frame.add(new JLabel());
    frame.add(buttonPanel);
    
    // Xử lý sự kiện lưu
    btnSave.addActionListener(e -> {
        try {
            // 1. Kiểm tra rỗng 
            if (txtMaChuyenBay.getText().trim().isEmpty() || txtNgayBay.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(frame, "Vui lòng nhập ít nhất Mã chuyến bay và Ngày bay!", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 2. Khởi tạo đối tượng ChuyenBay
            DAL.ChuyenBay cb = new DAL.ChuyenBay();
            
            // Gán dữ liệu dạng Chuỗi (String)
            cb.setMaChuyenBay(txtMaChuyenBay.getText().trim());
            cb.setMaMayBay(txtMaMayBay.getText().trim());
            cb.setMaHangHangKhong(txtMaHangHangKhong.getText().trim());
            cb.setMaSanBayDi(txtMaSanBayDi.getText().trim());
            cb.setMaSanBayDen(txtMaSanBayDen.getText().trim());
            cb.setNgayBay(txtNgayBay.getText().trim());
            cb.setGioBay(txtGioBay.getText().trim());
            cb.setGioDen(txtGioDen.getText().trim());
            
            // 3. Gán dữ liệu dạng số
            String strTongVe = txtTongSoVe.getText().trim().isEmpty() ? "0" : txtTongSoVe.getText().trim();
            String strDaBan = txtSoVeDaBan.getText().trim().isEmpty() ? "0" : txtSoVeDaBan.getText().trim();
            String strConLai = txtSoVeConLai.getText().trim().isEmpty() ? "0" : txtSoVeConLai.getText().trim();
            String strTien = txtTienVeThuVe.getText().trim().isEmpty() ? "0" : txtTienVeThuVe.getText().trim();

            cb.setTongSoVe(Integer.parseInt(strTongVe));
            cb.setSoVeDaBan(Integer.parseInt(strDaBan));
            cb.setSoVeConLai(Integer.parseInt(strConLai));
            cb.setTienVeThuVe(Long.parseLong(strTien));

            // 4. Gọi DAO
            DAO.ChuyenBayDAO dao = new DAO.ChuyenBayDAO();
            boolean isSuccess = dao.them(cb);
            if (isSuccess) {
                JOptionPane.showMessageDialog(frame, "Thêm chuyến bay thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                frame.dispose();
                btnDoc_cbActionPerformed(evt); 
            } else {
                JOptionPane.showMessageDialog(frame, "Thêm thất bại! Mã chuyến bay có thể đã tồn tại hoặc sai Khóa ngoại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(frame, "Lỗi nhập liệu: Tổng vé, Số vé, Tiền vé phải là số nguyên!", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(frame, "Lỗi hệ thống: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    });
    
    // Xử lý sự kiện hủy
    btnCancel.addActionListener(e -> frame.dispose());
    
    // Hiển thị Form
    frame.setLocationRelativeTo(this);
    frame.setVisible(true);
}           
    
    
    //========================= SỰ KIỆN CHO QUẢN LÝ KHÁCH HÀNG ========================
    private void btnDoc_khActionPerformed(java.awt.event.ActionEvent evt) {                                          
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tbl_kh.getModel();
        model.setRowCount(0); 
        
        DAO.KhachHangDAO dao = new DAO.KhachHangDAO();
        java.util.ArrayList<DAL.KhachHang> list = dao.docTatCa();
        
        for (DAL.KhachHang kh : list) {
            model.addRow(new Object[]{
                kh.getMaKhachHang(), kh.getHo(), kh.getTen(), 
                null,
                kh.getNgaySinh(), kh.getSoDienThoai(), kh.getEmail()
            });
        }
    }
    private void btnThem_khActionPerformed(java.awt.event.ActionEvent evt) {                                           
        JFrame frame = new JFrame("Thêm Khách Hàng mới");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 500);
        
        JTextField txtMaKhachHang = new JTextField();
        JTextField txtHo = new JTextField();
        JTextField txtTen = new JTextField();
        JTextField txtMaHHK = new JTextField();
        JTextField txtNgaySinh = new JTextField();
        JTextField txtSDT = new JTextField();
        JTextField txtEmail = new JTextField();
        
        frame.add(new JLabel("Mã Khách Hàng:"));
        frame.add(txtMaKhachHang);
        frame.add(new JLabel("Họ:"));
        frame.add(txtHo);
        frame.add(new JLabel("Tên:"));
        frame.add(txtTen);
        frame.add(new JLabel("Mã Hãng Hàng Không:"));
        frame.add(txtMaHHK);
        frame.add(new JLabel("Ngày Sinh:"));
        frame.add(txtNgaySinh);
        frame.add(new JLabel("Số Điện Thoại:"));
        frame.add(txtSDT);
        frame.add(new JLabel("Email:"));
        frame.add(txtEmail);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    
    }                                          

private void btnSua_khActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // 1. Kiểm tra xem người dùng đã chọn dòng nào trên bảng chưa
        int selectedRow = tbl_kh.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một khách hàng trên bảng để sửa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy Mã Khách Hàng từ cột 0 của bảng
        String maKH = tbl_kh.getValueAt(selectedRow, 0).toString();

        // 2. Khởi tạo Form Sửa
        JFrame frame = new JFrame("Sửa Thông Tin Khách Hàng");
        frame.setLayout(new java.awt.GridLayout(0, 2, 10, 10));
        frame.setSize(400, 400);
        
        JTextField txtMaKhachHang = new JTextField(maKH);
        txtMaKhachHang.setEditable(false); // BẮT BUỘC: Khóa mã lại không cho sửa
        JTextField txtHo = new JTextField();
        JTextField txtTen = new JTextField();
        JTextField txtNgaySinh = new JTextField();
        JTextField txtSDT = new JTextField();
        JTextField txtEmail = new JTextField();

        // 3. Lấy dữ liệu CHUẨN từ Database đắp lên Form (Chống lỗi lệch cột trên giao diện)
        try {
            Connection conn = DBConnection.getConnection();
            String sqlSelect = "SELECT * FROM khachhang WHERE maKhachHang = ?";
            PreparedStatement psSelect = conn.prepareStatement(sqlSelect);
            psSelect.setString(1, maKH);
            ResultSet rs = psSelect.executeQuery();
            
            if(rs.next()) {
                txtHo.setText(rs.getString("ho"));
                txtTen.setText(rs.getString("ten"));
                txtNgaySinh.setText(rs.getString("ngaySinh"));
                txtSDT.setText(rs.getString("soDienThoai"));
                txtEmail.setText(rs.getString("email"));
            }
            conn.close();
        } catch (Exception ex) {
            System.out.println("Lỗi load dữ liệu khách hàng: " + ex.getMessage());
        }

        // 4. Gắn các ô nhập liệu vào Form (Bỏ qua cột Mã HHK vì CSDL không có)
        frame.add(new JLabel("Mã Khách Hàng (Khóa):")); frame.add(txtMaKhachHang);
        frame.add(new JLabel("Họ:")); frame.add(txtHo);
        frame.add(new JLabel("Tên:")); frame.add(txtTen);
        frame.add(new JLabel("Ngày Sinh (YYYY-MM-DD):")); frame.add(txtNgaySinh);
        frame.add(new JLabel("Số Điện Thoại:")); frame.add(txtSDT);
        frame.add(new JLabel("Email:")); frame.add(txtEmail);
        
        JButton btnSave = new JButton("💾 Cập Nhật");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        // 5. Sự kiện khi bấm nút Cập Nhật
        btnSave.addActionListener(e -> {
            try {
                // Kết nối Database và dùng lệnh UPDATE
                Connection conn = DBConnection.getConnection();
                String sqlUpdate = "UPDATE khachhang SET ho=?, ten=?, ngaySinh=?, soDienThoai=?, email=? WHERE maKhachHang=?";
                PreparedStatement ps = conn.prepareStatement(sqlUpdate);

                ps.setString(1, txtHo.getText().trim());
                ps.setString(2, txtTen.getText().trim());
                ps.setString(3, txtNgaySinh.getText().trim());
                ps.setString(4, txtSDT.getText().trim());
                ps.setString(5, txtEmail.getText().trim());
                
                // Điều kiện
                ps.setString(6, txtMaKhachHang.getText().trim());

                int rowsUpdated = ps.executeUpdate();

                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(frame, "Cập nhật khách hàng thành công!");
                    frame.dispose();
                    loadKhachHang();
                } else {
                    JOptionPane.showMessageDialog(frame, "Cập nhật thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
                conn.close();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(frame, "Lỗi hệ thống: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        });
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }          

    private void btnXoa_khActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = tbl_kh.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một khách hàng trên bảng để xóa!");
            return;
        }

        // Lấy mã khách hàng từ cột 0
        String maKH = tbl_kh.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa khách hàng " + maKH + "?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            DAO.KhachHangDAO dao = new DAO.KhachHangDAO();
            if (dao.xoa(maKH)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                btnDoc_khActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }                                  

    private void btnTim_khActionPerformed(java.awt.event.ActionEvent evt) {                                           
    String maKH = JOptionPane.showInputDialog(this, "Nhập mã khách hàng:");

    if (maKH != null && !maKH.trim().isEmpty()) {
        try {
            Connection conn = DBConnection.getConnection();

            String sql = "SELECT * FROM khachhang WHERE maKhachHang = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, maKH);

            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tbl_kh.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("maKhachHang"),  // sửa lại đúng tên
                    rs.getString("tenKhachHang"),
                    rs.getString("cccd"),
                    rs.getString("soDienThoai"),
                    rs.getString("email")
                });
            }

            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}                              
    
    
    //========================= SỰ KIỆN CHO QUẢN LÝ VÉ ========================
    private void btnDoc_veActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // Lấy model
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tbl_ve.getModel();
        model.setRowCount(0);
        
        try {
            DAO.VeDAO dao = new DAO.VeDAO();
            java.util.ArrayList<DAL.Ve> list = dao.docTatCa();
            
            for (DAL.Ve ve : list) {
                model.addRow(new Object[]{
                    ve.getMaVe(), 
                    ve.getMaChuyenBay(), 
                    ve.getMaGhe(), 
                    ve.getLoaiVe(), 
                    ve.getGiaVe()
                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi đọc dữ liệu Vé: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnThem_veActionPerformed(java.awt.event.ActionEvent evt) {                                           
        JFrame frame = new JFrame("Thêm Vé");
        frame.setLayout(new GridLayout(0, 2, 10, 10));
        frame.setSize(400, 300);
        
        JTextField txtMaChuyenBay = new JTextField();
        JTextField txtMaVe = new JTextField();
        JTextField txtMaGhe = new JTextField();
        JTextField txtLoaiVe= new JTextField();
        JTextField txtGiaVe= new JTextField();

        frame.add(new JLabel("Mã Vé:"));
        frame.add(txtMaVe);
        frame.add(new JLabel("Mã Chuyến Bay:"));
        frame.add(txtMaChuyenBay);
        frame.add(new JLabel("Mã Ghế:"));
        frame.add(txtMaGhe);
        frame.add(new JLabel("Lọai Vé:"));
        frame.add(txtLoaiVe);
        frame.add(new JLabel("Giá Vé:"));
        frame.add(txtGiaVe);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {});
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }                                          

    private void btnSua_veActionPerformed(java.awt.event.ActionEvent evt) {                                          
    // 1. Kiểm tra chọn
    int selectedRow = tbl_ve.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một vé trên bảng để sửa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Tạo form Sửa
    JFrame frame = new JFrame("Sửa Thông Tin Vé");
    frame.setLayout(new java.awt.GridLayout(0, 2, 10, 10));
    frame.setSize(400, 300);
    
    JTextField txtMaVe = new JTextField();
    JTextField txtMaChuyenBay = new JTextField();
    JTextField txtMaGhe = new JTextField();
    JTextField txtLoaiVe = new JTextField();
    JTextField txtGiaVe = new JTextField();

    txtMaVe.setText(tbl_ve.getValueAt(selectedRow, 0).toString());
    txtMaVe.setEditable(false);
    txtMaChuyenBay.setText(tbl_ve.getValueAt(selectedRow, 1) != null ? tbl_ve.getValueAt(selectedRow, 1).toString() : "");
    txtMaGhe.setText(tbl_ve.getValueAt(selectedRow, 2) != null ? tbl_ve.getValueAt(selectedRow, 2).toString() : "");
    txtLoaiVe.setText(tbl_ve.getValueAt(selectedRow, 3) != null ? tbl_ve.getValueAt(selectedRow, 3).toString() : "");
    txtGiaVe.setText(tbl_ve.getValueAt(selectedRow, 4) != null ? tbl_ve.getValueAt(selectedRow, 4).toString() : "");

    frame.add(new JLabel("Mã Vé (Không đổi):")); frame.add(txtMaVe);
    frame.add(new JLabel("Mã Chuyến Bay:")); frame.add(txtMaChuyenBay);
    frame.add(new JLabel("Mã Ghế:")); frame.add(txtMaGhe);
    frame.add(new JLabel("Loại Vé:")); frame.add(txtLoaiVe);
    frame.add(new JLabel("Giá Vé:")); frame.add(txtGiaVe);
    
    JButton btnSave = new JButton("💾 Cập Nhật");
    JButton btnCancel = new JButton("❌ Hủy");
    
    JPanel buttonPanel = new JPanel();
    buttonPanel.add(btnSave);
    buttonPanel.add(btnCancel);
    
    frame.add(new JLabel());
    frame.add(buttonPanel);
    
    //nút Cập Nhật
    btnSave.addActionListener(e -> {
            try {
                DAL.Ve ve = new DAL.Ve();
                ve.setMaVe(txtMaVe.getText().trim());
                ve.setMaChuyenBay(txtMaChuyenBay.getText().trim());
                ve.setMaGhe(txtMaGhe.getText().trim());
                ve.setLoaiVe(txtLoaiVe.getText().trim());
                
                // Ép kiểu 
                String strGia = txtGiaVe.getText().trim().isEmpty() ? "0" : txtGiaVe.getText().trim();
                ve.setGiaVe(Double.parseDouble(strGia));
                
                DAO.VeDAO dao = new DAO.VeDAO();
                if (dao.sua(ve)) {
                    JOptionPane.showMessageDialog(frame, "Cập nhật vé thành công!");
                    frame.dispose();
                    btnDoc_veActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(frame, "Cập nhật thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(frame, "Giá vé phải là số!", "Lỗi Nhập Liệu", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(frame, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        });
        
        btnCancel.addActionListener(e -> frame.dispose());
        
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }
    
    private void btnXoa_veActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int selectedRow = tbl_ve.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một vé trên bảng để xóa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String maVe = tbl_ve.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn hủy vé " + maVe + " không?", "Xác nhận Hủy Vé", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                DAO.VeDAO dao = new DAO.VeDAO();
                if (dao.xoa(maVe)) {
                    JOptionPane.showMessageDialog(this, "Đã hủy vé thành công!");
                    btnDoc_veActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(this, "Hủy vé thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi hệ thống: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }                                       

    private void btnTim_veActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String maVe = JOptionPane.showInputDialog(this, "Nhập mã vé:");

        if (maVe != null && !maVe.trim().isEmpty()) {
            try {
                Connection conn = DBConnection.getConnection();

                String sql = "SELECT * FROM ve WHERE maVe = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, maVe);

                ResultSet rs = ps.executeQuery();

                DefaultTableModel model = (DefaultTableModel) tbl_ve.getModel();
                model.setRowCount(0);

                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("maVe"),
                        rs.getString("maChuyenBay"),
                        rs.getString("maKH"),
                        rs.getString("giaVe"),
                        rs.getString("loaiVe")
                    });
                }

                conn.close();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }                                      
    
    
    //========================= SỰ KIỆN CHO QUẢN LÝ CTKM ========================
    private void btnDoc_ctkmActionPerformed(java.awt.event.ActionEvent evt) {                                          
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable4.getModel();
        model.setRowCount(0); 
        
        try {
            DAO.CTKMDAO dao = new DAO.CTKMDAO();
            java.util.ArrayList<DAL.CTKM> list = dao.docTatCa(); 
            
            for (DAL.CTKM km : list) {
                model.addRow(new Object[]{
                    km.getMaCTKM(),
                    km.getTenCTKM(),
                    km.getNgayBD(),
                    km.getNgayKT(),
                    km.getNoiDung()
                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi đọc dữ liệu CTKM: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnThem_ctkmActionPerformed(java.awt.event.ActionEvent evt) {                                             
        JFrame frame = new JFrame("Thêm Chương Trình Khuyến Mãi");
        frame.setLayout(new java.awt.GridLayout(0, 2, 10, 10));
        frame.setSize(400, 300);
        
        JTextField txtMaCTKM = new JTextField();
        JTextField txtTenCTKM = new JTextField();
        JTextField txtNgayBD = new JTextField();
        JTextField txtNgayKT = new JTextField();
        JTextField txtNoiDung = new JTextField();

        frame.add(new JLabel("Mã CTKM:")); frame.add(txtMaCTKM);
        frame.add(new JLabel("Tên CTKM:")); frame.add(txtTenCTKM);
        frame.add(new JLabel("Ngày Bắt Đầu (YYYY-MM-DD):")); frame.add(txtNgayBD);
        frame.add(new JLabel("Ngày Kết Thúc (YYYY-MM-DD):")); frame.add(txtNgayKT);
        frame.add(new JLabel("Nội Dung:")); frame.add(txtNoiDung);
        
        JButton btnSave = new JButton("💾 Lưu");
        JButton btnCancel = new JButton("❌ Hủy");
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        frame.add(new JLabel());
        frame.add(buttonPanel);
        
        btnSave.addActionListener(e -> {
            try {
                DAL.CTKM km = new DAL.CTKM();
                km.setMaCTKM(txtMaCTKM.getText().trim());
                km.setTenCTKM(txtTenCTKM.getText().trim());
                km.setNgayBD(txtNgayBD.getText().trim());
                km.setNgayKT(txtNgayKT.getText().trim());
                km.setNoiDung(txtNoiDung.getText().trim());

                DAO.CTKMDAO dao = new DAO.CTKMDAO();
                if (dao.them(km)) { 
                    JOptionPane.showMessageDialog(frame, "Thêm CTKM thành công!");
                    frame.dispose();
                    btnDoc_ctkmActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(frame, "Thêm thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(frame, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        });
        
        btnCancel.addActionListener(e -> frame.dispose());
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }             

    private void btnSua_ctkmActionPerformed(java.awt.event.ActionEvent evt) {                                            
    int selectedRow = jTable4.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một CTKM trên bảng để sửa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    JFrame frame = new JFrame("Sửa Chương Trình Khuyến Mãi");
    frame.setLayout(new java.awt.GridLayout(0, 2, 10, 10));
    frame.setSize(400, 300);
    
    JTextField txtMaCTKM = new JTextField();
    JTextField txtTenCTKM = new JTextField();
    JTextField txtNgayBD = new JTextField();
    JTextField txtNgayKT = new JTextField();
    JTextField txtNoiDung = new JTextField();

    // Lấy dữ liệu từ bảng
    txtMaCTKM.setText(jTable4.getValueAt(selectedRow, 0).toString());
    txtMaCTKM.setEditable(false);
    txtTenCTKM.setText(jTable4.getValueAt(selectedRow, 1) != null ? jTable4.getValueAt(selectedRow, 1).toString() : "");
    txtNgayBD.setText(jTable4.getValueAt(selectedRow, 2) != null ? jTable4.getValueAt(selectedRow, 2).toString() : "");
    txtNgayKT.setText(jTable4.getValueAt(selectedRow, 3) != null ? jTable4.getValueAt(selectedRow, 3).toString() : "");
    txtNoiDung.setText(jTable4.getValueAt(selectedRow, 4) != null ? jTable4.getValueAt(selectedRow, 4).toString() : "");

    frame.add(new JLabel("Mã CTKM (Khóa):")); frame.add(txtMaCTKM);
    frame.add(new JLabel("Tên CTKM:")); frame.add(txtTenCTKM);
    frame.add(new JLabel("Ngày Bắt Đầu:")); frame.add(txtNgayBD);
    frame.add(new JLabel("Ngày Kết Thúc:")); frame.add(txtNgayKT);
    frame.add(new JLabel("Nội Dung:")); frame.add(txtNoiDung);
    
    JButton btnSave = new JButton("💾 Cập Nhật");
    JButton btnCancel = new JButton("❌ Hủy");
    
    JPanel buttonPanel = new JPanel();
    buttonPanel.add(btnSave);
    buttonPanel.add(btnCancel);
    
    btnSave.addActionListener(e -> {
        try {
            DAL.CTKM km = new DAL.CTKM();
            km.setMaCTKM(txtMaCTKM.getText().trim());
            km.setTenCTKM(txtTenCTKM.getText().trim());
            km.setNgayBD(txtNgayBD.getText().trim());
            km.setNgayKT(txtNgayKT.getText().trim());
            km.setNoiDung(txtNoiDung.getText().trim());
            
            DAO.CTKMDAO dao = new DAO.CTKMDAO();
            if (dao.sua(km)) { 
                JOptionPane.showMessageDialog(frame, "Cập nhật thành công!");
                frame.dispose();
                btnDoc_ctkmActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(frame, "Cập nhật thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(frame, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    });
    
    btnCancel.addActionListener(e -> frame.dispose());
    frame.setLocationRelativeTo(this);
    frame.setVisible(true);
}

    private void btnXoa_ctkmActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // 1. Kiểm tra xem người dùng đã chọn dòng nào
        int selectedRow = jTable4.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một chương trình khuyến mãi trên bảng để xóa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Lấy Mã CTKM từ cột
        String maCTKM = jTable4.getValueAt(selectedRow, 0).toString();

        // 3. Hiển thị hộp thoại xác nhận
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc chắn muốn xóa chương trình khuyến mãi: " + maCTKM + "?", 
                "Xác nhận Xóa", 
                JOptionPane.YES_NO_OPTION);
                
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                DAO.CTKMDAO dao = new DAO.CTKMDAO();
                
                if (dao.xoa(maCTKM)) { 
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    btnDoc_ctkmActionPerformed(evt); 
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại! Có thể mã CTKM này đang được dùng trong Hóa Đơn hoặc Chuyến Bay.", "Lỗi Ràng Buộc", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi hệ thống: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }                                         

    private void btnTim_ctkmActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String ma = JOptionPane.showInputDialog(this, "Nhập mã CTKM:");

        if (ma != null && !ma.trim().isEmpty()) {
            try {
                Connection conn = DBConnection.getConnection();

                String sql = "SELECT * FROM ctkm WHERE maCTKM = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, ma);

                ResultSet rs = ps.executeQuery();

                DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
                model.setRowCount(0);

                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("maCTKM"),
                        rs.getString("tenCTKM"),
                        rs.getString("ngayBD"),
                        rs.getString("ngayKT"),
                        rs.getString("noiDung")
                    });
                }

                conn.close();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }                  
   
    //========================= SỰ KIỆN CHO BÁO CÁO ========================
    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try {
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tbl_cb.getModel();
            int tongChuyenBay = model.getRowCount();
            int tongVeDaBan = 0;
            long tongDoanhThu = 0;

            for (int i = 0; i < tongChuyenBay; i++) {
                Object objBan = model.getValueAt(i, 9);
                Object objTien = model.getValueAt(i, 11);
                
                if (objBan != null && !objBan.toString().isEmpty()) {
                    tongVeDaBan += Integer.parseInt(objBan.toString());
                }
                if (objTien != null && !objTien.toString().isEmpty()) {
                    tongDoanhThu += Long.parseLong(objTien.toString());
                }
            }

            jTextArea1.setText("========== BẢNG THỐNG KÊ TỔNG QUAN ==========\n\n");
            jTextArea1.append("Tổng số chuyến bay đang khai thác: " + tongChuyenBay + " chuyến\n");
            jTextArea1.append("Tổng số vé đã bán ra: " + tongVeDaBan + " vé\n");
            jTextArea1.append("Tổng doanh thu toàn hệ thống: " + String.format("%,d", tongDoanhThu) + " VNĐ\n\n");
            jTextArea1.append("=============================================\n");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi thống kê: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try {
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tbl_cb.getModel();
            int rowCount = model.getRowCount();

            jTextArea1.setText("========== BÁO CÁO DOANH THU THEO CHUYẾN BAY ==========\n\n");
            jTextArea1.append(String.format("%-15s %-20s %-15s %-20s\n", "Mã CB", "Ngày Bay", "Đã Bán", "Doanh Thu (VNĐ)"));
            jTextArea1.append("-----------------------------------------------------------------------\n");

            for (int i = 0; i < rowCount; i++) {
                String maCB = model.getValueAt(i, 0) != null ? model.getValueAt(i, 0).toString() : "";
                String ngayBay = model.getValueAt(i, 5) != null ? model.getValueAt(i, 5).toString() : "";
                
                Object objBan = model.getValueAt(i, 9);
                int daBan = (objBan != null && !objBan.toString().isEmpty()) ? Integer.parseInt(objBan.toString()) : 0;
                
                Object objTien = model.getValueAt(i, 11);
                long doanhThu = (objTien != null && !objTien.toString().isEmpty()) ? Long.parseLong(objTien.toString()) : 0;

                jTextArea1.append(String.format("%-15s %-20s %-15d %,20d\n", maCB, ngayBay, daBan, doanhThu));
            }
            jTextArea1.append("-----------------------------------------------------------------------\n");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi xuất báo cáo: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }                                     

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String maVe = JOptionPane.showInputDialog(this, "Nhập Mã Vé để xem hóa đơn (Ví dụ: VTH01):");
        if (maVe != null && !maVe.trim().isEmpty()) {
            try {
                Connection conn = DBConnection.getConnection();
                
                String sqlVe = "SELECT * FROM ve WHERE maVe = ?";
                PreparedStatement psVe = conn.prepareStatement(sqlVe);
                psVe.setString(1, maVe.trim());
                ResultSet rsVe = psVe.executeQuery();
                
                if (!rsVe.next()) {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy vé với mã: " + maVe, "Lỗi", JOptionPane.ERROR_MESSAGE);
                    conn.close();
                    return;
                }
                
                String maCB = rsVe.getString("maChuyenBay");
                String maGhe = rsVe.getString("maGhe");
                String loaiVe = rsVe.getString("loaiVe");
                double giaVe = rsVe.getDouble("giaVe");
                
                String sqlCB = "SELECT * FROM chuyenbay WHERE maChuyenBay = ?";
                PreparedStatement psCB = conn.prepareStatement(sqlCB);
                psCB.setString(1, maCB);
                ResultSet rsCB = psCB.executeQuery();
                
                jTextArea1.setText("================ HÓA ĐƠN THANH TOÁN ================\n\n");
                jTextArea1.append("Mã Vé: " + maVe.toUpperCase() + "\n");
                
                java.time.LocalDateTime now = java.time.LocalDateTime.now();
                java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
                jTextArea1.append("Ngày in: " + now.format(formatter) + "\n");
                jTextArea1.append("----------------------------------------------------\n");
                jTextArea1.append("CHI TIẾT CHUYẾN BAY:\n");
                
                if (rsCB.next()) {
                    jTextArea1.append("- Chuyến bay: " + maCB + " (" + rsCB.getString("maHangHangKhong") + ")\n");
                    jTextArea1.append("- Hành trình: Sân bay " + rsCB.getString("maSanBayDi") + " ---> Sân bay " + rsCB.getString("maSanBayDen") + "\n");
                    jTextArea1.append("- Khởi hành: " + rsCB.getString("GioBay") + " ngày " + rsCB.getString("NgayBay") + "\n");
                } else {
                    jTextArea1.append("- Chuyến bay: " + maCB + " (Chưa có thông tin chi tiết)\n");
                }

                jTextArea1.append("----------------------------------------------------\n");
                jTextArea1.append("CHI TIẾT VÉ:\n");
                jTextArea1.append("- Mã Ghế: " + maGhe + "\n");
                jTextArea1.append("- Hạng Vé: " + loaiVe + "\n");
                jTextArea1.append("----------------------------------------------------\n");
                
                jTextArea1.append("TỔNG TIỀN THANH TOÁN: " + String.format("%,.0f", giaVe) + " VNĐ\n\n");
                jTextArea1.append("========= CẢM ƠN QUÝ KHÁCH ĐÃ ĐẶT CHUYẾN BAY =========\n");

                conn.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi khi tạo hóa đơn: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // Kiểm tra
        if (jTextArea1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có nội dung nào để xuất PDF! Vui lòng nhấn 'Xem Hóa Đơn' hoặc 'Thống Kê' trước.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            JOptionPane.showMessageDialog(this, "Đang mở hộp thoại xuất PDF / Máy in...", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            boolean isPrinted = jTextArea1.print(); 
            
            if (isPrinted) {
                JOptionPane.showMessageDialog(this, "Thao tác thành công!", "Hoàn tất", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Bạn đã hủy thao tác.", "Đã hủy", JOptionPane.WARNING_MESSAGE);
            }
        } catch (java.awt.print.PrinterException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi xuất PDF: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnXuatExcel_cbActionPerformed(java.awt.event.ActionEvent evt) {                                                
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tbl_cb.getModel();
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu trên bảng để xuất!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu file Excel (CSV)");
        
        if (fileChooser.showSaveDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileChooser.getSelectedFile();
            String path = file.getAbsolutePath();
            if (!path.toLowerCase().endsWith(".csv")) {
                path += ".csv";
            }

            try (java.io.PrintWriter pw = new java.io.PrintWriter(new java.io.File(path), "UTF-8")) {
                pw.write('\ufeff');
                
                for (int i = 0; i < model.getColumnCount(); i++) {
                    pw.print(model.getColumnName(i) + (i == model.getColumnCount() - 1 ? "" : ","));
                }
                pw.println();

                //In Dữ liệu từng dòng
                for (int i = 0; i < model.getRowCount(); i++) {
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        Object val = model.getValueAt(i, j);
                        pw.print((val == null ? "" : val.toString()) + (j == model.getColumnCount() - 1 ? "" : ","));
                    }
                    pw.println();
                }
                JOptionPane.showMessageDialog(this, "Xuất file Excel thành công tại:\n" + path);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi xuất file: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void btnNhapExcel_cbActionPerformed(java.awt.event.ActionEvent evt) {                                                
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Chọn file Excel (CSV) để nhập vào Database");
        
        if (fileChooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileChooser.getSelectedFile();

            try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.InputStreamReader(new java.io.FileInputStream(file), "UTF-8"))) {
                String line;
                boolean isFirstLine = true;
                DAO.ChuyenBayDAO dao = new DAO.ChuyenBayDAO();
                int count = 0;

                // Đọc từng dòng trong file Excel
                while ((line = br.readLine()) != null) {
                    if (isFirstLine) { 
                        isFirstLine = false;
                        continue;
                    }
                    
                    String[] data = line.split(",");
                    if (data.length >= 12) {
                        DAL.ChuyenBay cb = new DAL.ChuyenBay();
                        cb.setMaChuyenBay(data[0].trim());
                        cb.setMaMayBay(data[1].trim());
                        cb.setMaHangHangKhong(data[2].trim());
                        cb.setMaSanBayDi(data[3].trim());
                        cb.setMaSanBayDen(data[4].trim());
                        cb.setNgayBay(data[5].trim());
                        cb.setGioBay(data[6].trim());
                        cb.setGioDen(data[7].trim());
                        
                        cb.setTongSoVe(Integer.parseInt(data[8].trim().isEmpty() ? "0" : data[8].trim()));
                        cb.setSoVeDaBan(Integer.parseInt(data[9].trim().isEmpty() ? "0" : data[9].trim()));
                        cb.setSoVeConLai(Integer.parseInt(data[10].trim().isEmpty() ? "0" : data[10].trim()));
                        cb.setTienVeThuVe(Long.parseLong(data[11].trim().isEmpty() ? "0" : data[11].trim()));

                        if(dao.them(cb)) { 
                            count++; 
                        }
                    }
                }
                JOptionPane.showMessageDialog(this, "Đã nhập thành công " + count + " chuyến bay vào Database!");
                btnDoc_cbActionPerformed(evt);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi đọc file Excel: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    public void loadChuyenBay() {
        DefaultTableModel model = (DefaultTableModel) tbl_cb.getModel();
        model.setRowCount(0);

        try {
            Connection conn = DBConnection.getConnection();
            String sql = "SELECT * FROM chuyenbay";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("maChuyenBay"),
                    rs.getString("maMayBay"),
                    rs.getString("maHangHangKhong"),
                    rs.getString("maSanBayDi"),
                    rs.getString("maSanBayDen"),
                    rs.getString("NgayBay"),
                    rs.getString("GioBay"),
                    rs.getString("GioDen"),
                    rs.getInt("TongSoVe"),
                    rs.getInt("SoVeDaBan"),
                    rs.getInt("SoVeConLai"),
                    rs.getLong("TienVeThuVe")
                });
            }

            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void loadKhachHang() {
        DefaultTableModel model = (DefaultTableModel) tbl_kh.getModel();
        model.setRowCount(0);

        try {
            Connection conn = DBConnection.getConnection();
            String sql = "SELECT * FROM khachhang";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("maKhachHang"),
                    rs.getString("ho"),
                    rs.getString("ten"),
                    rs.getString("ngaySinh"),
                    rs.getString("soDienThoai"),
                    rs.getString("email")
                });
            }

            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void loadVe() {
        DefaultTableModel model = (DefaultTableModel) tbl_ve.getModel();
        model.setRowCount(0);

        try {
            Connection conn = DBConnection.getConnection();
            String sql = "SELECT * FROM ve";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("maVe"),
                    rs.getString("maChuyenBay"),
                    rs.getString("maGhe"),
                    rs.getString("giaVe"),
                    rs.getString("loaiVe")
                });
            }

            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadCTKM() {
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        model.setRowCount(0);

        try {
            Connection conn = DBConnection.getConnection();
            String sql = "SELECT * FROM ctkm";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("maCTKM"),
                    rs.getString("tenCTKM"),
                    rs.getString("ngayBD"),
                    rs.getString("ngayKT"),
                    rs.getString("noiDung")
                });
            }

            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnBaoCao;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnSua_cb;
    private javax.swing.JButton btnSua_ctkm;
    private javax.swing.JButton btnSua_kh;
    private javax.swing.JButton btnSua_ve;
    private javax.swing.JButton btnThem_cb;
    private javax.swing.JButton btnThem_ctkm;
    private javax.swing.JButton btnThem_kh;
    private javax.swing.JButton btnThem_ve;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTim_cb;
    private javax.swing.JButton btnTim_ctkm;
    private javax.swing.JButton btnTim_kh;
    private javax.swing.JButton btnTim_ve;
    private javax.swing.JButton btnXoa_cb;
    private javax.swing.JButton btnXoa_ctkm;
    private javax.swing.JButton btnXoa_kh;
    private javax.swing.JButton btnXoa_ve;
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbl_cb;
    private javax.swing.JTable tbl_kh;
    private javax.swing.JTable tbl_ve;
    // End of variables declaration                   
}
